project_id = "qgenaltkjtlvwfgykpxq"

[functions.send-invite-email]
verify_jwt = false

[functions.clicksign]
verify_jwt = true

[functions.clicksign-webhook]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.calculadora-financeira]
verify_jwt = false

[functions.isa-system-data]
verify_jwt = false

[functions.isa-actions]
verify_jwt = false

[functions.manychat]
verify_jwt = false

[functions.manychat-webhook]
verify_jwt = false

[functions.isa-auto-process]
verify_jwt = false

[functions.api-hub]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.calendar-sync]
verify_jwt = false

[functions.google-drive]
verify_jwt = false

[functions.drive-sync]
verify_jwt = false

[functions.google-oauth]
verify_jwt = false

[functions.followup-automation]
verify_jwt = false

[functions.isa-check-appointments]
verify_jwt = false

[functions.isa-scheduler]
verify_jwt = false

[functions.isa-reply-manychat]
verify_jwt = false
