
INSERT INTO modelos_peticao (nome, arquivo_url, variaveis) VALUES
('Venda Casada — Banco Santander', '/templates/venda_casada_santander.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Seguro Não Contratado — Bradesco', '/templates/seguro_nao_contratado_bradesco.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Venda Casada — Caixa Econômica Federal', '/templates/venda_casada_cef.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Venda Casada — Financiamento Veículo', '/templates/venda_casada_financiamento_veiculo.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Tarifa Bancária — Bradesco', '/templates/tarifa_bancaria_bradesco.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Revisional — Crefisa', '/templates/revisional_crefisa.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Empréstimo Fraudulento — INSS', '/templates/emprestimo_fraudulento_inss.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Renovação Empréstimo Fraudulento — INSS', '/templates/renovacao_emprestimo_fraudulento_inss.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Venda Casada — INSS (Facta)', '/templates/venda_casada_inss.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Idoso INSS — RMC (Santander)', '/templates/idoso_inss_rmc.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"},{"textoOriginal":"","variavel":"IDOSO_IDADE"}]'),
('Servidor Aposentado Idoso — Banco Industrial', '/templates/servidor_aposentado_idoso.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"},{"textoOriginal":"","variavel":"IDOSO_IDADE"}]'),
('Servidor Público — Banco Daycoval', '/templates/servidor_publico.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Policial Militar — Promoção (Turma 2005)', '/templates/policial_militar_promocao.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG_MILITAR"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Diferença Salarial — Professor', '/templates/dif_salarial_professor.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"DOC_ID"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Promoção — SES', '/templates/promocao_ses.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"DOC_ID"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Cancelamento de Voo — Azul Linhas Aéreas', '/templates/cancelamento_voo_azul.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]'),
('Cancelamento de Voo — Avianca', '/templates/cancelamento_voo_avianca.docx', '[{"textoOriginal":"","variavel":"NOME_COMPLETO"},{"textoOriginal":"","variavel":"QUALIFICACAO"},{"textoOriginal":"","variavel":"CPF"},{"textoOriginal":"","variavel":"RG"},{"textoOriginal":"","variavel":"ENDERECO_CLIENTE"},{"textoOriginal":"","variavel":"TIPO_ACAO"},{"textoOriginal":"","variavel":"REU_NOME"},{"textoOriginal":"","variavel":"REU_CNPJ"},{"textoOriginal":"","variavel":"REU_ENDERECO"},{"textoOriginal":"","variavel":"VARA_JUIZO"},{"textoOriginal":"","variavel":"COMARCA"}]');
