ALTER TABLE public.processos
  ADD COLUMN IF NOT EXISTS numero_complementar text,
  ADD COLUMN IF NOT EXISTS descricao text,
  ADD COLUMN IF NOT EXISTS marcadores text,
  ADD COLUMN IF NOT EXISTS area text,
  ADD COLUMN IF NOT EXISTS fase text,
  ADD COLUMN IF NOT EXISTS assunto_cnj text,
  ADD COLUMN IF NOT EXISTS segredo_justica boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS data_distribuicao date,
  ADD COLUMN IF NOT EXISTS data_citacao date,
  ADD COLUMN IF NOT EXISTS data_recebimento date,
  ADD COLUMN IF NOT EXISTS data_arquivamento date,
  ADD COLUMN IF NOT EXISTS data_encerramento date,
  ADD COLUMN IF NOT EXISTS valor_provisionado numeric,
  ADD COLUMN IF NOT EXISTS probabilidade text,
  ADD COLUMN IF NOT EXISTS monitorar_push boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS tipo_orgao_julgador text,
  ADD COLUMN IF NOT EXISTS sistema_judicial text,
  ADD COLUMN IF NOT EXISTS complemento_enderecamento text;